### PR TITLE
Add ability to change selected date

### PR DESCRIPTION
**Pull request by defint**
Helo! 
In my case I should show the last date of the period inside range picker.
So, this PR allows to set what actual date should be shown as initial page.

Example usage:
```
RangePicker(
          selectedDate: period.end,
          selectedPeriod: period,
...
```

### CODE REVIEW

**Comment by MariaMelnik** [comment]
@defint Hi, thank you for the PR. I will check it in couple days.

**Comment by vasilich6107** [comment]
Hi @MariaMelnik 
Any updates about this PR?

**Comment by MariaMelnik** [comment]
@vasilich6107 hi,
I thought that selectedDate and selectedPeriod can be confusing.
So I keep this PR as reminder to implement this feature.
Seems now the right time to do it =) 

I added ```initiallyShowDate``` property for ```DayPicker```, ```WeekPicker``` and ```RangePicker```. 
You can set it if you want to have specific initial month.

Use this dependency: ```flutter_date_pickers: ^0.2.2```

**Comment by MariaMelnik** [comment]
@defint I am closing this but thank you so march for your impact!

**Pull request closed without merging**
